### ISSUE TITLE
if the imgRefUrl contains question mark, imgRefUrl must be concatinate with "&" and not with "?"

### ISSUE THREAD

**Issue by dburucu** [sularome/Zoomple#6]
src = imgRefUrl+"?" + new Date().getTime();

must be:

src = imgRefUrl + (imgRefUrl.indexOf("?") > -1?"&":"?") + "time=" + new Date().getTime();

**Comment by dburucu** [comment]
solved in #7

**Comment by sularome** [comment]
Thanks!
